version: "3.7"
services:
  database:
    image: postgres:latest
    container_name: "ecoin_database"
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - ecoin_postgresql_volume:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      ecoin-compose-network:
        ipv4_address: 172.21.0.2

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: "pgadmin"
    restart: always
    env_file: .env
    ports:
      - "9090:80"
    depends_on:
      - database
    networks:
      - ecoin-compose-network
    volumes:
      - ecoin_pgadmin_volume:/var/pgadmin/data

  server:
    image: ecointracker:server
    container_name: "ecoin_server"
    restart: always
    ports:
      - "10000:10000"
    volumes:
      - ecoin_server_volume:/var/lib/ecoin_server/data
    networks:
      - ecoin-compose-network
volumes:
  ecoin_server_volume:
  ecoin_postgresql_volume:
  ecoin_pgadmin_volume:

networks:
  ecoin-compose-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/24
          gateway: 172.21.0.1
